// Auto-generated verified luxury catalog seed data
export interface SeedProduct {
  name: string;
  slug: string;
  sku: string;
  categorySlug: string;
  brandSlug: string;
  price: number;
  compareAtPrice: number;
  shortDescription: string;
  description: string;
  featured: boolean;
  localImage: string;
  unsplashUrl: string;
}

export const SEED_PRODUCTS: SeedProduct[] = [
  {
    name: "Chronos & Co Royal Chronograph Watch",
    slug: "chronos-co-royal-chronograph",
    sku: "LUX-TIM-1001",
    categorySlug: "timepieces",
    brandSlug: "chronos-co",
    price: 18500,
    compareAtPrice: 22000,
    shortDescription:
      "Precision Swiss automatic chronograph with polished stainless steel casing and sapphire crystal.",
    description:
      "Engineered for horological purists, the Royal Chronograph features a certified Swiss mechanical movement, ceramic tachymeter bezel, and hand-stitched alligator strap.",
    featured: true,
    localImage: "/images/products/timepieces/chronos-co-royal-chronograph.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800",
  },
  {
    name: "Atelier V Heritage Dual-Time Watch",
    slug: "atelier-v-heritage-dual-time",
    sku: "LUX-TIM-1002",
    categorySlug: "timepieces",
    brandSlug: "atelier-v",
    price: 14200,
    compareAtPrice: 16500,
    shortDescription: "Italian-designed GMT timepiece with 24-hour dual time zone display.",
    description:
      "The Heritage Dual-Time pairs Italian minimalist aesthetics with an ultra-reliable mechanical movement, housed in a rose-gold PVD steel case.",
    featured: false,
    localImage: "/images/products/timepieces/atelier-v-heritage-dual-time.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?q=80&w=800",
  },
  {
    name: "Nordic Craft Minimalist Mesh Watch",
    slug: "nordic-craft-minimalist-watch",
    sku: "LUX-TIM-1003",
    categorySlug: "timepieces",
    brandSlug: "nordic-craft",
    price: 9800,
    compareAtPrice: 11500,
    shortDescription: "Ultra-slim Scandinavian dress watch with woven steel mesh band.",
    description:
      "Embodying Nordic functional minimalism, this timepiece features a sunray silver dial, 6mm ultra-thin casing, and quick-release Milanese mesh strap.",
    featured: true,
    localImage: "/images/products/timepieces/nordic-craft-minimalist-watch.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=800",
  },
  {
    name: "Solis Gold Perpetual Calendar Watch",
    slug: "solis-gold-perpetual-calendar",
    sku: "LUX-TIM-1004",
    categorySlug: "timepieces",
    brandSlug: "solis",
    price: 24500,
    compareAtPrice: 28000,
    shortDescription: "18K yellow gold plated astronomical complication timepiece.",
    description:
      "Handcrafted in Solis studios, this astronomical timepiece displays moon phase, month, date, and 24-hour cycle beneath double-domed anti-reflective sapphire.",
    featured: false,
    localImage: "/images/products/timepieces/solis-gold-perpetual-calendar.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1547996160-81dfa63595aa?q=80&w=800",
  },
  {
    name: "Obsidian Matte Black Titanium Diver",
    slug: "obsidian-matte-black-diver",
    sku: "LUX-TIM-1005",
    categorySlug: "timepieces",
    brandSlug: "obsidian",
    price: 16800,
    compareAtPrice: 19500,
    shortDescription: "300m water-resistant titanium diver with ceramic unidirectional bezel.",
    description:
      "Crafted from aerospace-grade Grade 5 titanium with black DLC coating. Super-LumiNova BGW9 indices provide superior underwater legibility.",
    featured: false,
    localImage: "/images/products/timepieces/obsidian-matte-black-diver.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?q=80&w=800",
  },
  {
    name: "Chronos & Co Skeleton Mechanical Timepiece",
    slug: "chronos-co-skeleton-mechanical",
    sku: "LUX-TIM-1006",
    categorySlug: "timepieces",
    brandSlug: "chronos-co",
    price: 21000,
    compareAtPrice: 25000,
    shortDescription: "Exhibition dial showcasing hand-finished escapement and gear trains.",
    description:
      "A masterclass in open-worked horology. Both the dial and case back provide unobstructed views of the oscillating balance wheel and blued steel screws.",
    featured: true,
    localImage: "/images/products/timepieces/chronos-co-skeleton-mechanical.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1587865501868-36104829d7db?q=80&w=800",
  },
  {
    name: "Zephyr Nautical Yachting Chronometer",
    slug: "zephyr-nautical-yacht-timer",
    sku: "LUX-TIM-1007",
    categorySlug: "timepieces",
    brandSlug: "zephyr",
    price: 13500,
    compareAtPrice: 15800,
    shortDescription: "Regatta countdown chronograph with marine grade stainless steel case.",
    description:
      "Tested in offshore racing conditions, featuring a 10-minute regatta timer, ocean blue guilloché dial, and vulcanized FKM rubber strap.",
    featured: false,
    localImage: "/images/products/timepieces/zephyr-nautical-yacht-timer.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1533139502658-0198f920d8e8?q=80&w=800",
  },
  {
    name: "Kensington Classic Roman Dress Watch",
    slug: "kensington-classic-roman-dress",
    sku: "LUX-TIM-1008",
    categorySlug: "timepieces",
    brandSlug: "kensington",
    price: 11900,
    compareAtPrice: 13900,
    shortDescription: "British heritage dress watch with blued hands and Roman numerals.",
    description:
      "Classic London tailoring distilled into a timepiece. Features heat-blued Breguet-style hands, enamel dial, and a polished stainless steel 38mm case.",
    featured: false,
    localImage: "/images/products/timepieces/kensington-classic-roman-dress.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1508057198894-247b23fe5ade?q=80&w=800",
  },
  {
    name: "Atelier V Monolith Aviator Pilot Watch",
    slug: "atelier-v-monolith-pilot-watch",
    sku: "LUX-TIM-1009",
    categorySlug: "timepieces",
    brandSlug: "atelier-v",
    price: 15400,
    compareAtPrice: 17800,
    shortDescription: "High-contrast pilot watch with anti-magnetic soft iron inner cage.",
    description:
      "Directly inspired by mid-century navigation clocks, offering oversized luminous Arabic numerals, onion crown, and distressed saddle leather strap.",
    featured: false,
    localImage: "/images/products/timepieces/atelier-v-monolith-pilot-watch.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?q=80&w=800",
  },
  {
    name: "Obsidian Tourbillon Precision Watch",
    slug: "obsidian-tourbillon-timepiece",
    sku: "LUX-TIM-1010",
    categorySlug: "timepieces",
    brandSlug: "obsidian",
    price: 32000,
    compareAtPrice: 38000,
    shortDescription: "Flying tourbillon complication with forge carbon and titanium case.",
    description:
      "The pinnacle of high horology at LuxStore. Features a 60-second flying tourbillon cage, twin barrels delivering 72 hours of power reserve, and sapphire bridges.",
    featured: true,
    localImage: "/images/products/timepieces/obsidian-tourbillon-timepiece.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?q=80&w=800",
  },
  {
    name: "Atelier V Tuscany Calfskin Weekender Duffel",
    slug: "atelier-v-tuscany-calfskin-duffel",
    sku: "LUX-LEA-1001",
    categorySlug: "leather-bags",
    brandSlug: "atelier-v",
    price: 19800,
    compareAtPrice: 24000,
    shortDescription: "Full-grain Italian vegetable-tanned leather overnight travel holdall.",
    description:
      "Handcrafted in Florence using vegetable-tanned Tuscan calfskin that patinas richly over decades. Features solid brass YKK Excella zippers and reinforced base feet.",
    featured: true,
    localImage: "/images/products/leather-bags/atelier-v-tuscany-calfskin-duffel.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=800",
  },
  {
    name: "Saffiano Executive Structured Briefcase",
    slug: "saffiano-executive-structured-briefcase",
    sku: "LUX-LEA-1002",
    categorySlug: "leather-bags",
    brandSlug: "saffiano",
    price: 16500,
    compareAtPrice: 19800,
    shortDescription: "Scratch-resistant cross-hatch leather business briefcase.",
    description:
      "Engineered for executive demands, featuring Saffiano leather treatment, dedicated 16-inch padded laptop sleeve, dual gussets, and lockable front latch.",
    featured: false,
    localImage: "/images/products/leather-bags/saffiano-executive-structured-briefcase.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=800",
  },
  {
    name: "Terra Leather Classic Courier Messenger",
    slug: "terra-leather-courier-messenger",
    sku: "LUX-LEA-1003",
    categorySlug: "leather-bags",
    brandSlug: "terra-leather",
    price: 12400,
    compareAtPrice: 14900,
    shortDescription: "Vintage saddle leather crossbody messenger bag with magnetic snaps.",
    description:
      "Rugged yet refined, this courier bag features full-grain pull-up leather, heavy cotton canvas lining, and quick-access exterior slip pockets.",
    featured: false,
    localImage: "/images/products/leather-bags/terra-leather-courier-messenger.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=800",
  },
  {
    name: "Heritage Guild Hand-Woven Leather Tote",
    slug: "heritage-guild-woven-leather-tote",
    sku: "LUX-LEA-1004",
    categorySlug: "leather-bags",
    brandSlug: "heritage-guild",
    price: 17200,
    compareAtPrice: 20500,
    shortDescription: "Artisan hand-woven intrecciato calfskin open tote.",
    description:
      "Over 40 hours of manual weaving go into each tote. Supple nappa strips create a timeless geometric texture, paired with sturdy rolled handles.",
    featured: true,
    localImage: "/images/products/leather-bags/heritage-guild-woven-leather-tote.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800",
  },
  {
    name: "Solis Handcrafted Suede Leather Holdall",
    slug: "solis-suede-weekend-holdall",
    sku: "LUX-LEA-1005",
    categorySlug: "leather-bags",
    brandSlug: "solis",
    price: 18900,
    compareAtPrice: 22500,
    shortDescription: "Rich tobacco suede travel duffel with smooth leather accents.",
    description:
      "Velvety water-treated Italian calf suede accented by vegetable-tanned bridle leather trims. Includes detachable padded shoulder strap and luggage tag.",
    featured: false,
    localImage: "/images/products/leather-bags/solis-suede-weekend-holdall.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1591561954557-26941169b49e?q=80&w=800",
  },
  {
    name: "Atelier V Minimalist Nappa Leather Sling",
    slug: "atelier-v-nappa-crossbody-sling",
    sku: "LUX-LEA-1006",
    categorySlug: "leather-bags",
    brandSlug: "atelier-v",
    price: 8900,
    compareAtPrice: 10500,
    shortDescription: "Ergonomic leather chest sling for daily essentials.",
    description:
      "Designed for seamless city transit. Ultra-soft Italian lamb nappa leather contours comfortably to the body with quick-release magnetic Fidlock buckle.",
    featured: false,
    localImage: "/images/products/leather-bags/atelier-v-nappa-crossbody-sling.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=800",
  },
  {
    name: "Kensington Oxford Leather Document Case",
    slug: "kensington-oxford-document-case",
    sku: "LUX-LEA-1007",
    categorySlug: "leather-bags",
    brandSlug: "kensington",
    price: 13800,
    compareAtPrice: 16200,
    shortDescription: "British bridle leather zip folio and document attaché.",
    description:
      "Hand-finished edges burnished with natural beeswax. Accommodates standard A4 folios, contracts, and slim tablets in formal elegance.",
    featured: false,
    localImage: "/images/products/leather-bags/kensington-oxford-document-case.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1571829604981-ea159f94e5ad?q=80&w=800",
  },
  {
    name: "Terra Leather Burnished Tan Carryall",
    slug: "terra-leather-burnished-carryall",
    sku: "LUX-LEA-1008",
    categorySlug: "leather-bags",
    brandSlug: "terra-leather",
    price: 15600,
    compareAtPrice: 18500,
    shortDescription: "Hand-burnished heritage leather duffel for getaways.",
    description:
      "Features artisanal edge-dying, antique brass hardware, shoe compartment with waterproof lining, and twin top carry handles.",
    featured: false,
    localImage: "/images/products/leather-bags/terra-leather-burnished-carryall.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1547949003-9792a18a2601?q=80&w=800",
  },
  {
    name: "Saffiano Monogram Zip-Top Leather Tote",
    slug: "saffiano-monogram-zip-tote",
    sku: "LUX-LEA-1009",
    categorySlug: "leather-bags",
    brandSlug: "saffiano",
    price: 14800,
    compareAtPrice: 17500,
    shortDescription: "Structured commuter tote with protective base studs.",
    description:
      "The ideal everyday carry for professionals. Structured silhouette maintains shape when set down, with zippered top security and organizational interior dividers.",
    featured: false,
    localImage: "/images/products/leather-bags/saffiano-monogram-zip-tote.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1598532163257-ae3c6b2524b6?q=80&w=800",
  },
  {
    name: "Heritage Guild Roamer Flap Leather Satchel",
    slug: "heritage-guild-roamer-flap-satchel",
    sku: "LUX-LEA-1010",
    categorySlug: "leather-bags",
    brandSlug: "heritage-guild",
    price: 13900,
    compareAtPrice: 16400,
    shortDescription: "Rugged oiled leather satchel with dual buckle closures.",
    description:
      "Treated with organic oils and waxes to resist unpredictable elements. Dual front bellow pockets and interior key lanyard.",
    featured: true,
    localImage: "/images/products/leather-bags/heritage-guild-roamer-flap-satchel.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?q=80&w=800",
  },
  {
    name: "Saffiano Bifold Textured Leather Wallet",
    slug: "saffiano-bifold-leather-wallet",
    sku: "LUX-WAL-1001",
    categorySlug: "wallets-folios",
    brandSlug: "saffiano",
    price: 4500,
    compareAtPrice: 5500,
    shortDescription: "Classic 8-card bifold in scratch-resistant cross-hatch calfskin.",
    description:
      "Slim profile designed to sit flat in suit jackets and trouser pockets. Features eight card slots, two bill compartments, and discreet RFID shielding.",
    featured: true,
    localImage: "/images/products/wallets-folios/saffiano-bifold-leather-wallet.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1627123424574-724758594e93?q=80&w=800",
  },
  {
    name: "Atelier V Slim RFID Leather Cardholder",
    slug: "atelier-v-slim-rfid-cardholder",
    sku: "LUX-WAL-1002",
    categorySlug: "wallets-folios",
    brandSlug: "atelier-v",
    price: 3200,
    compareAtPrice: 4000,
    shortDescription: "Ultra-compact 5-slot cardholder in full-grain Italian leather.",
    description:
      "Hand-painted edge seams and embossed Atelier V insignia. Perfect for minimalist EDC carriers seeking front-pocket convenience.",
    featured: false,
    localImage: "/images/products/wallets-folios/atelier-v-slim-rfid-cardholder.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=800",
  },
  {
    name: "Solis Gold-Embossed Zip Continental Wallet",
    slug: "solis-gold-zip-continental-wallet",
    sku: "LUX-WAL-1003",
    categorySlug: "wallets-folios",
    brandSlug: "solis",
    price: 6800,
    compareAtPrice: 8200,
    shortDescription: "Full-zip travel wallet with 12 card slots and zippered coin pouch.",
    description:
      "Crafted in emerald green calfskin with 24K gold-plated zipper pull and foil stamping. Accommodates boarding passes, cash currencies, and smartphone.",
    featured: false,
    localImage: "/images/products/wallets-folios/solis-gold-zip-continental-wallet.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1512414947060-048d53abb081?q=80&w=800",
  },
  {
    name: "Terra Leather Vegetable-Tanned Bifold",
    slug: "terra-leather-vegetable-bifold",
    sku: "LUX-WAL-1004",
    categorySlug: "wallets-folios",
    brandSlug: "terra-leather",
    price: 4900,
    compareAtPrice: 6000,
    shortDescription: "Natural patina leather bifold wallet with hand-waxed stitching.",
    description:
      "Starts in a warm caramel hue and deepens in color with every touch. Built with heavy-duty polyester stitching designed never to fray.",
    featured: false,
    localImage: "/images/products/wallets-folios/terra-leather-vegetable-bifold.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1614260937560-c749cc17da94?q=80&w=800",
  },
  {
    name: "Nordic Craft Minimalist Pocket Card Case",
    slug: "nordic-craft-pocket-card-case",
    sku: "LUX-WAL-1005",
    categorySlug: "wallets-folios",
    brandSlug: "nordic-craft",
    price: 2900,
    compareAtPrice: 3600,
    shortDescription: "Architectural folded leather card case with magnetic snap.",
    description:
      "Cut from a single piece of premium calf leather with origami folding principles, eliminating unnecessary seams for peak durability.",
    featured: false,
    localImage: "/images/products/wallets-folios/nordic-craft-pocket-card-case.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1586579724969-2cb96841bcb8?q=80&w=800",
  },
  {
    name: "Kensington Executive Leather Document Folio",
    slug: "kensington-executive-document-folio",
    sku: "LUX-WAL-1006",
    categorySlug: "wallets-folios",
    brandSlug: "kensington",
    price: 8500,
    compareAtPrice: 10200,
    shortDescription: "A4 leather portfolio folder with magnetic tab closure.",
    description:
      "Designed for board meetings and executive signings. Internal pockets for iPad Pro, legal pad, business cards, and fountain pen loop.",
    featured: true,
    localImage: "/images/products/wallets-folios/kensington-executive-document-folio.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1628483211662-9bcc692c46dc?q=80&w=800",
  },
  {
    name: "Obsidian Matte Black Leather Card Sleeve",
    slug: "obsidian-matte-black-card-sleeve",
    sku: "LUX-WAL-1007",
    categorySlug: "wallets-folios",
    brandSlug: "obsidian",
    price: 3400,
    compareAtPrice: 4200,
    shortDescription: "Anodized aluminum core wrapped in matte black calfskin.",
    description:
      "Features a pop-up quick ejection mechanism. Stores up to 6 cards securely without slipping, protected by Faraday RFID blocking.",
    featured: false,
    localImage: "/images/products/wallets-folios/obsidian-matte-black-card-sleeve.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1620109176813-e91290f6c795?q=80&w=800",
  },
  {
    name: "Heritage Guild Gusseted Coin Wallet",
    slug: "heritage-guild-gusseted-coin-wallet",
    sku: "LUX-WAL-1008",
    categorySlug: "wallets-folios",
    brandSlug: "heritage-guild",
    price: 4200,
    compareAtPrice: 5100,
    shortDescription: "Traditional heritage wallet with snap coin tray and billfold.",
    description:
      "A heritage European silhouette that pairs everyday card carriage with a convenient fold-out coin tray lined in soft pigskin.",
    featured: false,
    localImage: "/images/products/wallets-folios/heritage-guild-gusseted-coin-wallet.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1629958513881-a086d21383cd?q=80&w=800",
  },
  {
    name: "Atelier V Foldover Passport & Travel Folio",
    slug: "atelier-v-passport-travel-folio",
    sku: "LUX-WAL-1009",
    categorySlug: "wallets-folios",
    brandSlug: "atelier-v",
    price: 5600,
    compareAtPrice: 6800,
    shortDescription: "Global travel wallet holding passport, boarding pass, and SIM card.",
    description:
      "Crafted in supple French calf leather. Includes hidden cash stash, pen slot, and travel SIM ejector pin compartment.",
    featured: false,
    localImage: "/images/products/wallets-folios/atelier-v-passport-travel-folio.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1637486069202-b1163268c240?q=80&w=800",
  },
  {
    name: "Saffiano Compact Zip-Around Card Case",
    slug: "saffiano-compact-zip-card-case",
    sku: "LUX-WAL-1010",
    categorySlug: "wallets-folios",
    brandSlug: "saffiano",
    price: 3800,
    compareAtPrice: 4600,
    shortDescription: "Accordion style zip card case with gold-plated hardware.",
    description:
      "Opens wide in fan style to reveal 9 dedicated accordion slots. Fits folded bills and keys comfortably inside compact pocket sizing.",
    featured: false,
    localImage: "/images/products/wallets-folios/saffiano-compact-zip-card-case.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1637168943285-a8f9ea0dc3f5?q=80&w=800",
  },
  {
    name: "Ocular Optics Polarized Tortoiseshell Shades",
    slug: "ocular-optics-polarized-tortoiseshell",
    sku: "LUX-EYE-1001",
    categorySlug: "eyewear",
    brandSlug: "ocular-optics",
    price: 8200,
    compareAtPrice: 9800,
    shortDescription:
      "Hand-polished Italian Mazzucchelli acetate sunglasses with CR-39 polarized lenses.",
    description:
      "Features custom 5-barrel German hinges, amber tortoiseshell acetate, and category 3 polarized lenses with 100% UVA/UVB protection.",
    featured: true,
    localImage: "/images/products/eyewear/ocular-optics-polarized-tortoiseshell.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=800",
  },
  {
    name: "Aero Eyewear Ultralight Titanium Aviators",
    slug: "aero-eyewear-titanium-aviators",
    sku: "LUX-EYE-1002",
    categorySlug: "eyewear",
    brandSlug: "aero-eyewear",
    price: 9400,
    compareAtPrice: 11200,
    shortDescription: "Japanese beta-titanium aviator sunglasses weighing just 14 grams.",
    description:
      "Engineered with flexibility and featherweight balance. Finished with titanium nose pads and scratch-resistant hydrophobic green lenses.",
    featured: false,
    localImage: "/images/products/eyewear/aero-eyewear-titanium-aviators.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1508296695146-257a814070b4?q=80&w=800",
  },
  {
    name: "Nordic Craft Round Horn-Rimmed Frames",
    slug: "nordic-craft-round-optical-frames",
    sku: "LUX-EYE-1003",
    categorySlug: "eyewear",
    brandSlug: "nordic-craft",
    price: 7600,
    compareAtPrice: 9000,
    shortDescription: "Minimalist round optical frames with blue-light filtering lenses.",
    description:
      "Combines warm horn-effect bio-acetate with matte stainless steel bridge and temples. Prescription lens ready.",
    featured: false,
    localImage: "/images/products/eyewear/nordic-craft-round-optical-frames.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1574258495973-f010dfbb5371?q=80&w=800",
  },
  {
    name: "Obsidian Matte Black Square Sunglasses",
    slug: "obsidian-matte-black-square-sunglasses",
    sku: "LUX-EYE-1004",
    categorySlug: "eyewear",
    brandSlug: "obsidian",
    price: 8800,
    compareAtPrice: 10500,
    shortDescription: "Sculpted thick acetate frames with dark polarized smoke lenses.",
    description:
      "Bold geometric silhouette sculpted from high-density acetate blocks. Features beveled browline and subtle matte Obsidian hardware pins.",
    featured: true,
    localImage: "/images/products/eyewear/obsidian-matte-black-square-sunglasses.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?q=80&w=800",
  },
  {
    name: "Solis 24K Gold Accent Navigator Shades",
    slug: "solis-gold-navigator-sunglasses",
    sku: "LUX-EYE-1005",
    categorySlug: "eyewear",
    brandSlug: "solis",
    price: 10500,
    compareAtPrice: 12500,
    shortDescription: "Double-bridge navigator shades plated in 24K yellow gold.",
    description:
      "A luxury statement frame featuring precision-stamped filigree along the temples and warm gradient bronze polarized lenses.",
    featured: false,
    localImage: "/images/products/eyewear/solis-gold-navigator-sunglasses.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1577803645773-f96470509666?q=80&w=800",
  },
  {
    name: "Ocular Optics Classic Wayfarer Polarized",
    slug: "ocular-optics-classic-wayfarer",
    sku: "LUX-EYE-1006",
    categorySlug: "eyewear",
    brandSlug: "ocular-optics",
    price: 7900,
    compareAtPrice: 9200,
    shortDescription: "Timeless black acetate wayfarer frames with dark G15 polarized glass.",
    description:
      "The universal silhouette reimagined with premium hand-beveled edges, silver diamond rivets, and anti-reflective interior lens coating.",
    featured: false,
    localImage: "/images/products/eyewear/ocular-optics-classic-wayfarer.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1509695507497-903c140c43b0?q=80&w=800",
  },
  {
    name: "Aero Eyewear Rimless Titanium Sunglasses",
    slug: "aero-eyewear-rimless-titanium-shades",
    sku: "LUX-EYE-1007",
    categorySlug: "eyewear",
    brandSlug: "aero-eyewear",
    price: 9900,
    compareAtPrice: 11800,
    shortDescription: "Rimless precision eyewear with screwless hinge technology.",
    description:
      "Clean aesthetic lines offering zero visual obstruction. Custom diamond-cut lens beveling and hypoallergenic silicone temple tips.",
    featured: false,
    localImage: "/images/products/eyewear/aero-eyewear-rimless-titanium-shades.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1584036553516-bf83210aa16c?q=80&w=800",
  },
  {
    name: "Kensington Retro Clubmaster Sunglasses",
    slug: "kensington-retro-clubmaster-frames",
    sku: "LUX-EYE-1008",
    categorySlug: "eyewear",
    brandSlug: "kensington",
    price: 8400,
    compareAtPrice: 10000,
    shortDescription: "Classic British browline sunglasses in tortoiseshell and gold.",
    description:
      "Vintage mid-century styling featuring hand-riveted acetate browline, coin-edge rimwire, and mineral glass lenses.",
    featured: false,
    localImage: "/images/products/eyewear/kensington-retro-clubmaster-frames.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1511556532299-8f662fc26c06?q=80&w=800",
  },
  {
    name: "Zephyr Polarized Hydrophobic Sport Shades",
    slug: "zephyr-polarized-sport-shades",
    sku: "LUX-EYE-1009",
    categorySlug: "eyewear",
    brandSlug: "zephyr",
    price: 8100,
    compareAtPrice: 9600,
    shortDescription: "Active wrap-around shades with oleophobic water-repelling coatings.",
    description:
      "Built for marine sports and driving. Lightweight TR90 frame with non-slip Megol rubber nose pads and mirrored polarized lenses.",
    featured: false,
    localImage: "/images/products/eyewear/zephyr-polarized-sport-shades.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1566421966482-ad8076104d8e?q=80&w=800",
  },
  {
    name: "Ocular Optics Crystal Clear Acetate Frames",
    slug: "ocular-optics-crystal-acetate-frames",
    sku: "LUX-EYE-1010",
    categorySlug: "eyewear",
    brandSlug: "ocular-optics",
    price: 7800,
    compareAtPrice: 9200,
    shortDescription: "Translucent champagne crystal optical frames with visible core wire.",
    description:
      "Showcases custom engraved temple wire cores visible through crystal-clear organic cellulose acetate.",
    featured: false,
    localImage: "/images/products/eyewear/ocular-optics-crystal-acetate-frames.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1559070081-648fb00b2ed1?q=80&w=800",
  },
  {
    name: "Atelier V Reversible Calfskin Dress Belt",
    slug: "atelier-v-reversible-calfskin-belt",
    sku: "LUX-BLT-1001",
    categorySlug: "belts",
    brandSlug: "atelier-v",
    price: 5800,
    compareAtPrice: 6900,
    shortDescription: "Dual-sided black and cognac brown leather belt with twist buckle.",
    description:
      "Two distinct styling options in one luxurious piece. Switch between formal black and casual warm brown with a smooth twist of the polished palladium buckle.",
    featured: true,
    localImage: "/images/products/belts/atelier-v-reversible-calfskin-belt.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1624222247344-550fb60583dc?q=80&w=800",
  },
  {
    name: "Terra Leather Hand-Burnished Saddle Belt",
    slug: "terra-leather-hand-burnished-saddle-belt",
    sku: "LUX-BLT-1002",
    categorySlug: "belts",
    brandSlug: "terra-leather",
    price: 4900,
    compareAtPrice: 5800,
    shortDescription:
      "Heavyweight full-grain vegetable-tanned leather belt with solid brass buckle.",
    description:
      "Cut from 4mm thick English bridle leather. Solid cast brass roller buckle secured with hand-peened copper rivets for an heirloom lifespan.",
    featured: false,
    localImage: "/images/products/belts/terra-leather-hand-burnished-saddle-belt.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1711443982852-b3df5c563448?q=80&w=800",
  },
  {
    name: "Saffiano Textured Cross-Hatch Belt",
    slug: "saffiano-cross-hatch-leather-belt",
    sku: "LUX-BLT-1003",
    categorySlug: "belts",
    brandSlug: "saffiano",
    price: 5400,
    compareAtPrice: 6400,
    shortDescription: "35mm executive dress belt in scratch-resistant Saffiano calfskin.",
    description:
      "Crafted for tailored trousers and suits. Feveled edge profile, feathered construction, and brushed gunmetal buckle.",
    featured: false,
    localImage: "/images/products/belts/saffiano-cross-hatch-leather-belt.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1664286074176-5206ee5dc878?q=80&w=800",
  },
  {
    name: "Kensington British Stitch Tan Calfskin Belt",
    slug: "kensington-british-stitch-tan-belt",
    sku: "LUX-BLT-1004",
    categorySlug: "belts",
    brandSlug: "kensington",
    price: 5100,
    compareAtPrice: 6000,
    shortDescription: "Equestrian-inspired stitched tan leather dress belt.",
    description:
      "Contrasting cream perimeter saddle stitching, hand-creased borders, and a polished nickel harness buckle.",
    featured: false,
    localImage: "/images/products/belts/kensington-british-stitch-tan-belt.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1705493655920-20c572928501?q=80&w=800",
  },
  {
    name: "Solis Gold Monogram Buckle Dress Belt",
    slug: "solis-gold-buckle-formal-belt",
    sku: "LUX-BLT-1005",
    categorySlug: "belts",
    brandSlug: "solis",
    price: 6200,
    compareAtPrice: 7500,
    shortDescription: "Smooth black French calfskin belt with 24K gold-plated signature buckle.",
    description:
      "The quintessential formal evening belt. Seamless edge burnishing, calf leather lining, and high-shine gold monogram plaque.",
    featured: true,
    localImage: "/images/products/belts/solis-gold-buckle-formal-belt.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1752386223406-b3d94092d790?q=80&w=800",
  },
  {
    name: "Obsidian Matte Black Anodized Leather Belt",
    slug: "obsidian-matte-black-anodized-belt",
    sku: "LUX-BLT-1006",
    categorySlug: "belts",
    brandSlug: "obsidian",
    price: 5600,
    compareAtPrice: 6700,
    shortDescription: "Monochromatic all-black belt with matte black PVD hardware.",
    description:
      "Tumbled black pebble-grain leather paired with CNC-machined aircraft-grade aluminum buckle with matte ceramic bead blast finish.",
    featured: false,
    localImage: "/images/products/belts/obsidian-matte-black-anodized-belt.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1611937685025-8d1df67a80b6?q=80&w=800",
  },
  {
    name: "Heritage Guild Braided Woven Leather Belt",
    slug: "heritage-guild-braided-woven-belt",
    sku: "LUX-BLT-1007",
    categorySlug: "belts",
    brandSlug: "heritage-guild",
    price: 5200,
    compareAtPrice: 6200,
    shortDescription: "Hand-braided supple calf leather belt with prong buckle.",
    description:
      "Offers infinite micro-adjustability as the prong pushes directly through the woven weave. Ideal for chinos, linens, and smart-casual styling.",
    featured: false,
    localImage: "/images/products/belts/heritage-guild-braided-woven-belt.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1664286074240-d7059e004dff?q=80&w=800",
  },
  {
    name: "Nordic Craft Raw-Edge Minimalist Belt",
    slug: "nordic-craft-raw-edge-calfskin-belt",
    sku: "LUX-BLT-1008",
    categorySlug: "belts",
    brandSlug: "nordic-craft",
    price: 4700,
    compareAtPrice: 5600,
    shortDescription: "Unlined raw-edge bridle leather belt with architectural buckle.",
    description:
      "Celebrating honest materials with raw cut, hand-waxed edges and a minimalist square stainless steel frame buckle.",
    featured: false,
    localImage: "/images/products/belts/nordic-craft-raw-edge-calfskin-belt.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1679759022456-a7eae2257ba2?q=80&w=800",
  },
  {
    name: "Atelier V Formal Tuxedo Patent Leather Belt",
    slug: "atelier-v-tuxedo-patent-leather-belt",
    sku: "LUX-BLT-1009",
    categorySlug: "belts",
    brandSlug: "atelier-v",
    price: 6500,
    compareAtPrice: 7800,
    shortDescription: "Ultra-glossy black patent leather belt for black-tie dress codes.",
    description:
      "Exclusively crafted for tuxedo trousers, featuring glass-like mirror patent sheen and sleek concealed stitch-less construction.",
    featured: false,
    localImage: "/images/products/belts/atelier-v-tuxedo-patent-leather-belt.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1637868796504-32f45a96d5a0?q=80&w=800",
  },
  {
    name: "Zephyr Casual Webbed Canvas & Leather Belt",
    slug: "zephyr-webbed-canvas-leather-belt",
    sku: "LUX-BLT-1010",
    categorySlug: "belts",
    brandSlug: "zephyr",
    price: 3900,
    compareAtPrice: 4800,
    shortDescription: "Military-grade woven cotton canvas belt with bridle leather tabs.",
    description:
      "D-ring closure style with heavy-duty nautical canvas webbing, full-grain leather ends, and antique brass dual rings.",
    featured: false,
    localImage: "/images/products/belts/zephyr-webbed-canvas-leather-belt.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1664286022075-8e997e95bd17?q=80&w=800",
  },
  {
    name: "Apex Design Polycarbonate Carry-On Spinner",
    slug: "apex-design-polycarbonate-spinner",
    sku: "LUX-TRV-1001",
    categorySlug: "travel-cases",
    brandSlug: "apex-design",
    price: 18900,
    compareAtPrice: 22500,
    shortDescription:
      "Ultra-durable aerospace polycarbonate cabin luggage with 360 spinner wheels.",
    description:
      "Compliant with international cabin standards. Features an aluminum telescopic handle, TSA-approved combination locks, and whisper-quiet Hinomoto ball-bearing wheels.",
    featured: true,
    localImage: "/images/products/travel-cases/apex-design-polycarbonate-spinner.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1502301197179-65228ab57f78?q=80&w=800",
  },
  {
    name: "Heritage Guild Vintage Riveted Trunchette",
    slug: "heritage-guild-vintage-trunchette",
    sku: "LUX-TRV-1002",
    categorySlug: "travel-cases",
    brandSlug: "heritage-guild",
    price: 24000,
    compareAtPrice: 29000,
    shortDescription: "Hand-riveted vulcanized fiberboard and leather suitcase.",
    description:
      "Nostalgic golden-age travel aesthetics with modern longevity. Hand-stitched leather corner guards and solid brass dual latch closures.",
    featured: false,
    localImage: "/images/products/travel-cases/heritage-guild-vintage-trunchette.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1522199710521-72d69614c702?q=80&w=800",
  },
  {
    name: "Kensington Structured Hard-Shell Cabin Case",
    slug: "kensington-structured-cabin-luggage",
    sku: "LUX-TRV-1003",
    categorySlug: "travel-cases",
    brandSlug: "kensington",
    price: 17500,
    compareAtPrice: 21000,
    shortDescription: "British racing green hardside suitcase with cognac leather trim.",
    description:
      "A harmonious marriage of technical composite durability and classic leather accents. Internal compression system keeps suits wrinkle-free.",
    featured: false,
    localImage: "/images/products/travel-cases/kensington-structured-cabin-luggage.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1648737967037-96967e9151b5?q=80&w=800",
  },
  {
    name: "Atelier V Leather Toiletry & Dopp Kit",
    slug: "atelier-v-leather-toiletry-dopp-kit",
    sku: "LUX-TRV-1004",
    categorySlug: "travel-cases",
    brandSlug: "atelier-v",
    price: 6800,
    compareAtPrice: 8200,
    shortDescription: "Water-resistant lined calfskin travel wash bag.",
    description:
      "Wide doctor-bag style frame opening allows effortless access to grooming essentials. Lined with wipe-clean waterproof nylon interior.",
    featured: true,
    localImage: "/images/products/travel-cases/atelier-v-leather-toiletry-dopp-kit.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1631728370215-9440df2e29e3?q=80&w=800",
  },
  {
    name: "Velo Tech Compression Travel Packing Set",
    slug: "velo-tech-compression-packing-cubes",
    sku: "LUX-TRV-1005",
    categorySlug: "travel-cases",
    brandSlug: "velo-tech",
    price: 4500,
    compareAtPrice: 5500,
    shortDescription: "4-piece ultralight ripstop compression packing organizer set.",
    description:
      "Dual-zipper compression system reduces clothing volume by 40%. Built from water-resistant 210D ripstop nylon with breathable mesh panels.",
    featured: false,
    localImage: "/images/products/travel-cases/velo-tech-compression-packing-cubes.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1678667720699-5c0fc04ac166?q=80&w=800",
  },
  {
    name: "Apex Design 28-Inch Check-In Hardside Case",
    slug: "apex-design-check-in-hardside-28",
    sku: "LUX-TRV-1006",
    categorySlug: "travel-cases",
    brandSlug: "apex-design",
    price: 23500,
    compareAtPrice: 28000,
    shortDescription: "High-capacity 95L check-in suitcase with impact-absorbing shell.",
    description:
      "Engineered for long-haul expeditions. Micro-diamond texture resists scuffs, supported by reinforced corner bumpers and waterproof perimeter gasket.",
    featured: false,
    localImage: "/images/products/travel-cases/apex-design-check-in-hardside-28.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1678667590014-4769c04fc921?q=80&w=800",
  },
  {
    name: "Terra Leather Hanging Garment Suit Carrier",
    slug: "terra-leather-suit-carrier-garment-bag",
    sku: "LUX-TRV-1007",
    categorySlug: "travel-cases",
    brandSlug: "terra-leather",
    price: 15800,
    compareAtPrice: 18900,
    shortDescription: "Foldable leather and canvas tri-fold suit carrier.",
    description:
      "Transports up to three full suits and dress shoes without wrinkling. Hangs seamlessly in hotel closets via integrated brass swivel hook.",
    featured: false,
    localImage: "/images/products/travel-cases/terra-leather-suit-carrier-garment-bag.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1779364815233-84ec09c6d6d5?q=80&w=800",
  },
  {
    name: "Solis Structured Golden Vanity Travel Case",
    slug: "solis-golden-vanity-travel-case",
    sku: "LUX-TRV-1008",
    categorySlug: "travel-cases",
    brandSlug: "solis",
    price: 12500,
    compareAtPrice: 15000,
    shortDescription: "Hard-framed cosmetic and jewelry travel beauty trunk.",
    description:
      "Includes removable organizing trays, LED illuminated vanity mirror, and velvet-lined compartments for delicate jewelry and fragrances.",
    featured: false,
    localImage: "/images/products/travel-cases/solis-golden-vanity-travel-case.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1732605549677-6763dc81549b?q=80&w=800",
  },
  {
    name: "Obsidian Matte Black Aluminum Hybrid Case",
    slug: "obsidian-matte-black-aluminum-case",
    sku: "LUX-TRV-1009",
    categorySlug: "travel-cases",
    brandSlug: "obsidian",
    price: 26000,
    compareAtPrice: 31000,
    shortDescription: "Riveted aircraft-grade anodized aluminum cabin luggage.",
    description:
      "Zipper-less dual clasp closure system with heavy-duty neoprene seal, corner armor plates, and precision dampened leather-wrapped carry handles.",
    featured: true,
    localImage: "/images/products/travel-cases/obsidian-matte-black-aluminum-case.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1591719539805-81516f58dabc?q=80&w=800",
  },
  {
    name: "Heritage Guild Waxed Canvas Travel Holdall",
    slug: "heritage-guild-waxed-canvas-holdall",
    sku: "LUX-TRV-1010",
    categorySlug: "travel-cases",
    brandSlug: "heritage-guild",
    price: 14200,
    compareAtPrice: 17000,
    shortDescription: "Weatherproof 24oz waxed cotton canvas weekend travel bag.",
    description:
      "Tough as iron yet soft to the touch, this holdall handles inclement weather with ease, reinforced with bridal leather straps and heavy brass rivets.",
    featured: false,
    localImage: "/images/products/travel-cases/heritage-guild-waxed-canvas-holdall.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1706819399603-428b06afe3fc?q=80&w=800",
  },
  {
    name: "Nordic Craft Commuter Leather Backpack",
    slug: "nordic-craft-commuter-leather-backpack",
    sku: "LUX-BAK-1001",
    categorySlug: "backpacks",
    brandSlug: "nordic-craft",
    price: 14500,
    compareAtPrice: 17500,
    shortDescription: "Minimalist Scandinavian full-grain leather laptop backpack.",
    description:
      "Clean silhouette with zero extraneous exterior clutter. Concealed rear passport pocket, padded 16-inch laptop chamber, and breathable mesh back panel.",
    featured: true,
    localImage: "/images/products/backpacks/nordic-craft-commuter-leather-backpack.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1622560481156-01fc7e1693e6?q=80&w=800",
  },
  {
    name: "Apex Design Technical Ballistic Backpack",
    slug: "apex-design-ballistic-nylon-pack",
    sku: "LUX-BAK-1002",
    categorySlug: "backpacks",
    brandSlug: "apex-design",
    price: 12800,
    compareAtPrice: 15200,
    shortDescription: "1680D Cordura ballistic nylon urban transit daypack.",
    description:
      "Engineered for high-mileage commuters with waterproof YKK Aquaguard zippers, magnetic sternum strap, and luggage pass-through sleeve.",
    featured: false,
    localImage: "/images/products/backpacks/apex-design-ballistic-nylon-pack.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1642375352634-ad952121fdb3?q=80&w=800",
  },
  {
    name: "Atelier V Full-Grain Italian Leather Daypack",
    slug: "atelier-v-italian-calfskin-daypack",
    sku: "LUX-BAK-1003",
    categorySlug: "backpacks",
    brandSlug: "atelier-v",
    price: 16800,
    compareAtPrice: 20000,
    shortDescription: "Supple Florentine calfskin daypack with dual front pockets.",
    description:
      "Expertly assembled in Florence with hand-stitched leather pull tabs, herringbone twill lining, and padded ergonomic shoulder harnesses.",
    featured: false,
    localImage: "/images/products/backpacks/atelier-v-italian-calfskin-daypack.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1622560481979-f5b0174242a0?q=80&w=800",
  },
  {
    name: "Terra Leather Heritage Canvas Rucksack",
    slug: "terra-leather-heritage-canvas-rucksack",
    sku: "LUX-BAK-1004",
    categorySlug: "backpacks",
    brandSlug: "terra-leather",
    price: 11900,
    compareAtPrice: 14200,
    shortDescription: "Waxed cotton canvas rucksack with bridle leather buckle straps.",
    description:
      "Classic alpine explorer styling featuring cinch drawstring main compartment, side water bottle pockets, and vegetable-tanned leather lash squares.",
    featured: false,
    localImage: "/images/products/backpacks/terra-leather-heritage-canvas-rucksack.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1642375352724-8b523c67b8be?q=80&w=800",
  },
  {
    name: "Velo Tech Smart Transit Weatherproof Pack",
    slug: "velo-tech-smart-transit-laptop-pack",
    sku: "LUX-BAK-1005",
    categorySlug: "backpacks",
    brandSlug: "velo-tech",
    price: 13900,
    compareAtPrice: 16500,
    shortDescription: "Weatherproof rolltop backpack with integrated USB pass-through.",
    description:
      "Welded TPU coated nylon construction makes this pack 100% submersible. Features modular internal divider sleeves and magnetic FIDLOCK closures.",
    featured: true,
    localImage: "/images/products/backpacks/velo-tech-smart-transit-laptop-pack.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1591098204373-9116f28a74bf?q=80&w=800",
  },
  {
    name: "Kensington Classic Canvas & Suede Field Pack",
    slug: "kensington-british-field-backpack",
    sku: "LUX-BAK-1006",
    categorySlug: "backpacks",
    brandSlug: "kensington",
    price: 12200,
    compareAtPrice: 14800,
    shortDescription: "Heritage British outdoor backpack with suede base reinforcement.",
    description:
      "Heavyweight military twill accented with rich brown suede and antique brass eyelets. Features padded shoulder straps with felt underlay.",
    featured: false,
    localImage: "/images/products/backpacks/kensington-british-field-backpack.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1562869319-a1368ba7fe75?q=80&w=800",
  },
  {
    name: "Obsidian Stealth Tactical Luxury Backpack",
    slug: "obsidian-stealth-tactical-backpack",
    sku: "LUX-BAK-1007",
    categorySlug: "backpacks",
    brandSlug: "obsidian",
    price: 15900,
    compareAtPrice: 19000,
    shortDescription: "Matte black Cordura daypack with laser-cut MOLLE lash points.",
    description:
      "Blackout aesthetic with low-profile tactical utility. Includes suspended laptop cradle to protect against drops on hard floors.",
    featured: false,
    localImage: "/images/products/backpacks/obsidian-stealth-tactical-backpack.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1622560481336-b44c811b0958?q=80&w=800",
  },
  {
    name: "Solis Soft-Grain Designer Flap Backpack",
    slug: "solis-soft-grain-flap-backpack",
    sku: "LUX-BAK-1008",
    categorySlug: "backpacks",
    brandSlug: "solis",
    price: 17500,
    compareAtPrice: 21000,
    shortDescription: "Butter-soft pebbled leather backpack with gold clasp closure.",
    description:
      "Effortlessly elegant fashion backpack with drawcord top cinching beneath a structured leather flap with golden Solis hardware.",
    featured: false,
    localImage: "/images/products/backpacks/solis-soft-grain-flap-backpack.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1637851699902-846db7f0ec67?q=80&w=800",
  },
  {
    name: "Heritage Guild Expedition Heavyweight Pack",
    slug: "heritage-guild-expedition-twill-pack",
    sku: "LUX-BAK-1009",
    categorySlug: "backpacks",
    brandSlug: "heritage-guild",
    price: 13400,
    compareAtPrice: 16000,
    shortDescription: "Overland expedition backpack in olive green waxed twill.",
    description:
      "Built for lifetime durability. Thick harness leather straps, solid copper hardware rivets, and dual quick-access exterior zippered chambers.",
    featured: false,
    localImage: "/images/products/backpacks/heritage-guild-expedition-twill-pack.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1665832102447-a853788f620c?q=80&w=800",
  },
  {
    name: "Zephyr Marine Waterproof Rolltop Backpack",
    slug: "zephyr-all-weather-marine-rolltop",
    sku: "LUX-BAK-1010",
    categorySlug: "backpacks",
    brandSlug: "zephyr",
    price: 11500,
    compareAtPrice: 13800,
    shortDescription: "Heavy-duty waterproof rolltop backpack with high-frequency welded seams.",
    description:
      "Impervious to downpours, sea spray, and mud. Rolltop closure expands capacity up to 32 liters with external bungee cargo web.",
    featured: false,
    localImage: "/images/products/backpacks/zephyr-all-weather-marine-rolltop.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1562869323-d3d7be3e88a6?q=80&w=800",
  },
  {
    name: "Velo Tech Padded Leather Laptop Sleeve 14-inch",
    slug: "velo-tech-padded-leather-laptop-sleeve",
    sku: "LUX-TEC-1001",
    categorySlug: "tech-sleeves",
    brandSlug: "velo-tech",
    price: 4200,
    compareAtPrice: 5100,
    shortDescription: "Ultra-plush microfiber lined leather sleeve for MacBook Pro 14.",
    description:
      "Impact-absorbing EVA foam padding enveloped in smooth calfskin. Magnetic snap flap eliminates scratching from metal zippers.",
    featured: true,
    localImage: "/images/products/tech-sleeves/velo-tech-padded-leather-laptop-sleeve.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1689757855413-9e366c2011f1?q=80&w=800",
  },
  {
    name: "Atelier V Saffiano Leather MacBook Pro Folio",
    slug: "atelier-v-saffiano-macbook-folio",
    sku: "LUX-TEC-1002",
    categorySlug: "tech-sleeves",
    brandSlug: "atelier-v",
    price: 5400,
    compareAtPrice: 6500,
    shortDescription: "Structured 16-inch laptop folio with cable and stylus pockets.",
    description:
      "Durable cross-grain Saffiano leather folio with dual zippers that open flat to 180 degrees. Includes internal elastic cable organizers.",
    featured: false,
    localImage: "/images/products/tech-sleeves/atelier-v-saffiano-macbook-folio.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1708447135262-850979354fcf?q=80&w=800",
  },
  {
    name: "Nordic Craft Wool Felt & Leather iPad Sleeve",
    slug: "nordic-craft-wool-felt-tablet-sleeve",
    sku: "LUX-TEC-1003",
    categorySlug: "tech-sleeves",
    brandSlug: "nordic-craft",
    price: 3600,
    compareAtPrice: 4400,
    shortDescription: "Natural German Merino wool felt and vegetable-tanned leather sleeve.",
    description:
      "Eco-friendly 4mm thick natural wool felt provides organic cushioning and scratch protection, finished with a leather stylus loop.",
    featured: false,
    localImage: "/images/products/tech-sleeves/nordic-craft-wool-felt-tablet-sleeve.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1657603539862-5194b4ae171f?q=80&w=800",
  },
  {
    name: "Obsidian Shockproof Carbon Laptop Case",
    slug: "obsidian-shockproof-carbon-laptop-case",
    sku: "LUX-TEC-1004",
    categorySlug: "tech-sleeves",
    brandSlug: "obsidian",
    price: 4800,
    compareAtPrice: 5800,
    shortDescription: "Carbon-fiber composite hard sleeve with 360 corner bumper armor.",
    description:
      "Military standard drop protection in a sleek modern design. Molded ribbed exterior distributes impacts away from delicate screen corners.",
    featured: true,
    localImage: "/images/products/tech-sleeves/obsidian-shockproof-carbon-laptop-case.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1657603530277-b18bea816a78?q=80&w=800",
  },
  {
    name: "Terra Leather Hand-Stitched iPad Pro Folio",
    slug: "terra-leather-stitched-tablet-folio",
    sku: "LUX-TEC-1005",
    categorySlug: "tech-sleeves",
    brandSlug: "terra-leather",
    price: 4600,
    compareAtPrice: 5500,
    shortDescription: "Saddle-stitched leather envelope sleeve for 11 and 13-inch tablets.",
    description:
      "Handcrafted using thick pull-up leather that develops rich individual character. Dedicated slot for Apple Pencil / stylus charging.",
    featured: false,
    localImage: "/images/products/tech-sleeves/terra-leather-stitched-tablet-folio.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1508014938279-b7418e08350c?q=80&w=800",
  },
  {
    name: "Velo Tech Compartmentalized Cable Tech Pouch",
    slug: "velo-tech-cable-gear-organizer-pouch",
    sku: "LUX-TEC-1006",
    categorySlug: "tech-sleeves",
    brandSlug: "velo-tech",
    price: 3200,
    compareAtPrice: 3900,
    shortDescription: "Accordion style accessory organizer for chargers, power banks, and cords.",
    description:
      "Never untangle chargers again. Features 12 dedicated elastic loops, zippered mesh compartments, and water-resistant coated exterior.",
    featured: false,
    localImage: "/images/products/tech-sleeves/velo-tech-cable-gear-organizer-pouch.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1702561667986-113f3a9e06bc?q=80&w=800",
  },
  {
    name: "Saffiano Envelope Style Leather Laptop Case",
    slug: "saffiano-envelope-leather-laptop-case",
    sku: "LUX-TEC-1007",
    categorySlug: "tech-sleeves",
    brandSlug: "saffiano",
    price: 4900,
    compareAtPrice: 5900,
    shortDescription: "Slim document envelope profile for 13-inch ultrabooks.",
    description:
      "Clean tapered flap closure with hidden neodymium magnets. Slides effortlessly into tote bags and briefcases without adding bulk.",
    featured: false,
    localImage: "/images/products/tech-sleeves/saffiano-envelope-leather-laptop-case.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1611461527944-1a718332613b?q=80&w=800",
  },
  {
    name: "Kensington Quilted Leather Laptop Brief Sleeve",
    slug: "kensington-quilted-leather-brief-sleeve",
    sku: "LUX-TEC-1008",
    categorySlug: "tech-sleeves",
    brandSlug: "kensington",
    price: 5200,
    compareAtPrice: 6300,
    shortDescription: "Diamond quilted calfskin sleeve with retractable leather carry handle.",
    description:
      "Bridging the gap between sleeve and briefcase. Features diamond quilted padding, gold hardware, and tuck-away flat handles.",
    featured: false,
    localImage: "/images/products/tech-sleeves/kensington-quilted-leather-brief-sleeve.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1688296526377-4f64cfa7320b?q=80&w=800",
  },
  {
    name: "Apex Design Armor Molded Laptop Shell",
    slug: "apex-design-armor-molded-laptop-shell",
    sku: "LUX-TEC-1009",
    categorySlug: "tech-sleeves",
    brandSlug: "apex-design",
    price: 4400,
    compareAtPrice: 5300,
    shortDescription: "Crush-resistant molded EVA clamshell sleeve with dual zip.",
    description:
      "Allows using your laptop without removing it from the case via corner retention straps. Water-resistant polyurethane outer skin.",
    featured: false,
    localImage: "/images/products/tech-sleeves/apex-design-armor-molded-laptop-shell.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1688296524835-363a81b93921?q=80&w=800",
  },
  {
    name: "Heritage Guild Dual-Pocket Utility Tech Folio",
    slug: "heritage-guild-utility-tech-folio",
    sku: "LUX-TEC-1010",
    categorySlug: "tech-sleeves",
    brandSlug: "heritage-guild",
    price: 4700,
    compareAtPrice: 5700,
    shortDescription: "Waxed canvas and leather combination sleeve with external storage bellows.",
    description:
      "Heavyweight 18oz duck canvas front pocket carries bulky power adapters and mouse while leather main compartment shelters your computer.",
    featured: false,
    localImage: "/images/products/tech-sleeves/heritage-guild-utility-tech-folio.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1702561667794-c24589d98f05?q=80&w=800",
  },
  {
    name: "Sterling & Co 18K Solid Gold Signet Ring",
    slug: "sterling-co-18k-gold-signet-ring",
    sku: "LUX-JWL-1001",
    categorySlug: "fine-jewelry",
    brandSlug: "sterling-co",
    price: 14500,
    compareAtPrice: 17800,
    shortDescription: "Hand-carved cushion top signet ring in solid 18K yellow gold.",
    description:
      "Substantial 14g solid gold weight with hand-brushed satin face and mirror-polished beveled shoulders. Ready for custom bespoke seal engraving.",
    featured: true,
    localImage: "/images/products/fine-jewelry/sterling-co-18k-gold-signet-ring.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=800",
  },
  {
    name: "Obsidian Matte Black Titanium Cuff Bangle",
    slug: "obsidian-matte-black-titanium-cuff",
    sku: "LUX-JWL-1002",
    categorySlug: "fine-jewelry",
    brandSlug: "obsidian",
    price: 8800,
    compareAtPrice: 10500,
    shortDescription: "Beveled architectural open cuff bracelet in black DLC titanium.",
    description:
      "Engineered from hypoallergenic Grade 5 titanium with comfort-curve contouring and an ultra-durable diamond-like carbon matte finish.",
    featured: false,
    localImage: "/images/products/fine-jewelry/obsidian-matte-black-titanium-cuff.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1628785517892-dbcd2f2719ed?q=80&w=800",
  },
  {
    name: "Solis Diamond-Cut 14K Gold Cuban Link Chain",
    slug: "solis-diamond-cut-cuban-chain",
    sku: "LUX-JWL-1003",
    categorySlug: "fine-jewelry",
    brandSlug: "solis",
    price: 22000,
    compareAtPrice: 26500,
    shortDescription: "5mm solid 14K Italian yellow gold curb chain with double-safety clasp.",
    description:
      "Precision diamond-cut beveled links reflect light from every angle. 22-inch length with custom box lock safety mechanism.",
    featured: true,
    localImage: "/images/products/fine-jewelry/solis-diamond-cut-cuban-chain.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=800",
  },
  {
    name: "Nordic Craft Hammered 925 Silver Band Ring",
    slug: "nordic-craft-hammered-silver-band",
    sku: "LUX-JWL-1004",
    categorySlug: "fine-jewelry",
    brandSlug: "nordic-craft",
    price: 4900,
    compareAtPrice: 6000,
    shortDescription: "Organic hand-hammered 6mm sterling silver minimalist band.",
    description:
      "Each facet is struck individually by hand in Nordic Craft silversmith studios, creating an organic shimmering light return.",
    featured: false,
    localImage: "/images/products/fine-jewelry/nordic-craft-hammered-silver-band.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=800",
  },
  {
    name: "Sterling & Co Malachite & Onyx Beaded Bracelet",
    slug: "sterling-co-malachite-beaded-bracelet",
    sku: "LUX-JWL-1005",
    categorySlug: "fine-jewelry",
    brandSlug: "sterling-co",
    price: 5800,
    compareAtPrice: 7000,
    shortDescription: "8mm natural green malachite and matte onyx stones on stretch cord.",
    description:
      "Accented with hand-engraved 925 sterling silver logo bead. Selected for natural high-contrast banded green gemstone patterns.",
    featured: false,
    localImage: "/images/products/fine-jewelry/sterling-co-malachite-beaded-bracelet.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?q=80&w=800",
  },
  {
    name: "Solis Dual-Tone 18K Gold Braided Bangle",
    slug: "solis-braided-dual-tone-gold-bangle",
    sku: "LUX-JWL-1006",
    categorySlug: "fine-jewelry",
    brandSlug: "solis",
    price: 19500,
    compareAtPrice: 23500,
    shortDescription: "Intertwined 18K yellow gold and white gold twisted wire bangle.",
    description:
      "Master goldsmith creation intertwining alternating strands of yellow and white gold into a flexible, spring-hinged torque bangle.",
    featured: false,
    localImage: "/images/products/fine-jewelry/solis-braided-dual-tone-gold-bangle.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=800",
  },
  {
    name: "Obsidian Black Diamond Inlaid Titanium Ring",
    slug: "obsidian-black-diamond-titanium-ring",
    sku: "LUX-JWL-1007",
    categorySlug: "fine-jewelry",
    brandSlug: "obsidian",
    price: 11200,
    compareAtPrice: 13500,
    shortDescription: "Recessed channel set with 0.50 ctw treated black diamonds.",
    description:
      "Matte gunmetal titanium band with a recessed perimeter channel holding round brilliant-cut black diamonds in flush bezel setting.",
    featured: false,
    localImage: "/images/products/fine-jewelry/obsidian-black-diamond-titanium-ring.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1608042314453-ae338d80c427?q=80&w=800",
  },
  {
    name: "Heritage Guild Hand-Forged Silver Cable Bracelet",
    slug: "heritage-guild-forged-cable-bracelet",
    sku: "LUX-JWL-1008",
    categorySlug: "fine-jewelry",
    brandSlug: "heritage-guild",
    price: 7200,
    compareAtPrice: 8800,
    shortDescription: "Heavy twisted 925 sterling silver rope cable cuff.",
    description:
      "Inspired by traditional maritime knotting. Heavy 45-gram solid silver construction with oxidized vintage contrast finish.",
    featured: false,
    localImage: "/images/products/fine-jewelry/heritage-guild-forged-cable-bracelet.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=800",
  },
  {
    name: "Atelier V Double-Wrap Leather Hook Bracelet",
    slug: "atelier-v-leather-rose-gold-bracelet",
    sku: "LUX-JWL-1009",
    categorySlug: "fine-jewelry",
    brandSlug: "atelier-v",
    price: 4500,
    compareAtPrice: 5500,
    shortDescription: "Braided Italian calfskin leather with 18K rose gold plated anchor clasp.",
    description:
      "Supple double-wrap braided leather cord finished with hand-polished rose gold mechanical hook closure.",
    featured: false,
    localImage: "/images/products/fine-jewelry/atelier-v-leather-rose-gold-bracelet.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?q=80&w=800",
  },
  {
    name: "Sterling & Co Polished Platinum Classic Band",
    slug: "sterling-co-platinum-wedding-band",
    sku: "LUX-JWL-1010",
    categorySlug: "fine-jewelry",
    brandSlug: "sterling-co",
    price: 16800,
    compareAtPrice: 20000,
    shortDescription: "5mm comfort-fit solid 950 platinum wedding band.",
    description:
      "Substantial 950 pure platinum band with high-polish dome exterior and silky comfort-fit rounded interior curvature.",
    featured: false,
    localImage: "/images/products/fine-jewelry/sterling-co-platinum-wedding-band.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=800",
  },
  {
    name: "Sterling & Co Mother of Pearl Silver Cufflinks",
    slug: "sterling-co-mother-of-pearl-cufflinks",
    sku: "LUX-CUF-1001",
    categorySlug: "cufflinks",
    brandSlug: "sterling-co",
    price: 6800,
    compareAtPrice: 8200,
    shortDescription: "Iridescent Australian mother of pearl set in 925 sterling silver bezel.",
    description:
      "Natural organic sea pearl inlays catch the light with subtle opalescence. Equipped with solid silver swivel whale-tail back closures.",
    featured: true,
    localImage: "/images/products/cufflinks/sterling-co-mother-of-pearl-cufflinks.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1685392024138-36e7aade79f7?q=80&w=800",
  },
  {
    name: "Chronos & Co Mechanical Movement Cufflinks",
    slug: "chronos-co-movement-gear-cufflinks",
    sku: "LUX-CUF-1002",
    categorySlug: "cufflinks",
    brandSlug: "chronos-co",
    price: 8400,
    compareAtPrice: 10200,
    shortDescription: "Authentic vintage mechanical watch movement cufflinks with working gears.",
    description:
      "Actual 17-jewel mechanical watch movements preserved in stainless steel housings. Rubies, gears, and balance springs are fully visible.",
    featured: true,
    localImage: "/images/products/cufflinks/chronos-co-movement-gear-cufflinks.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1748840176432-4b2474189d52?q=80&w=800",
  },
  {
    name: "Obsidian Onyx & Matte Black Hexagonal Cufflinks",
    slug: "obsidian-onyx-titanium-cufflinks",
    sku: "LUX-CUF-1003",
    categorySlug: "cufflinks",
    brandSlug: "obsidian",
    price: 6200,
    compareAtPrice: 7500,
    shortDescription: "Hexagonal natural black onyx stone in matte black titanium frame.",
    description:
      "Clean geometric architecture for modern black-tie and tuxedo dress. Precision-beveled faceted natural onyx stones.",
    featured: false,
    localImage: "/images/products/cufflinks/obsidian-onyx-titanium-cufflinks.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1761110518837-689557b142bf?q=80&w=800",
  },
  {
    name: "Solis 18K Gold Woven Knot Formal Cufflinks",
    slug: "solis-18k-gold-woven-knot-cufflinks",
    sku: "LUX-CUF-1004",
    categorySlug: "cufflinks",
    brandSlug: "solis",
    price: 9500,
    compareAtPrice: 11500,
    shortDescription: "Timeless silk-knot inspired cufflinks crafted in solid 18K gold plate.",
    description:
      "A heritage formalwear staple. Three-dimensional woven cord motif with reassuring weight and secure swivel toggles.",
    featured: false,
    localImage: "/images/products/cufflinks/solis-18k-gold-woven-knot-cufflinks.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1708551362497-c6c6a9b85d8f?q=80&w=800",
  },
  {
    name: "Atelier V Hand-Stitched Leather Inlay Cufflinks",
    slug: "atelier-v-leather-inlay-cufflinks",
    sku: "LUX-CUF-1005",
    categorySlug: "cufflinks",
    brandSlug: "atelier-v",
    price: 5200,
    compareAtPrice: 6300,
    shortDescription: "Full-grain Italian calfskin inlays framed in polished rhodium.",
    description:
      "Matching leather trims with your luxury belts and shoes. Made from Tuscan vegetable-tanned leather inserts.",
    featured: false,
    localImage: "/images/products/cufflinks/atelier-v-leather-inlay-cufflinks.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1708551549968-6ed6644fbdc9?q=80&w=800",
  },
  {
    name: "Sterling & Co Oval Lapis Lazuli Cufflinks",
    slug: "sterling-co-lapis-lazuli-cufflinks",
    sku: "LUX-CUF-1006",
    categorySlug: "cufflinks",
    brandSlug: "sterling-co",
    price: 7400,
    compareAtPrice: 8900,
    shortDescription: "Deep ultramarine lapis lazuli gemstones with golden pyrite flecks.",
    description:
      "Hand-cut cabochon oval stones set in substantial 925 sterling silver rub-over bezels. Each pair is uniquely patterned by nature.",
    featured: false,
    localImage: "/images/products/cufflinks/sterling-co-lapis-lazuli-cufflinks.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1617960002868-099f4dea7567?q=80&w=800",
  },
  {
    name: "Kensington Engine-Turned Guilloché Cufflinks",
    slug: "kensington-guilloche-silver-cufflinks",
    sku: "LUX-CUF-1007",
    categorySlug: "cufflinks",
    brandSlug: "kensington",
    price: 6600,
    compareAtPrice: 7900,
    shortDescription: "Art-Deco barleycorn guilloché engraved sterling silver cufflinks.",
    description:
      "Traditional rose engine cutting creates a hypnotic geometric pattern beneath clear translucent vitreous enamel.",
    featured: false,
    localImage: "/images/products/cufflinks/kensington-guilloche-silver-cufflinks.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1592593044691-f45c8db82a48?q=80&w=800",
  },
  {
    name: "Obsidian Twill Carbon Fiber Inset Cufflinks",
    slug: "obsidian-carbon-fiber-stud-cufflinks",
    sku: "LUX-CUF-1008",
    categorySlug: "cufflinks",
    brandSlug: "obsidian",
    price: 5900,
    compareAtPrice: 7100,
    shortDescription: "Aerospace 3K twill carbon fiber inserts in brushed titanium bezels.",
    description:
      "Lightweight, ultra-modern automotive luxury aesthetics. Clear gloss resin protects the textured carbon fiber weave.",
    featured: false,
    localImage: "/images/products/cufflinks/obsidian-carbon-fiber-stud-cufflinks.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1507141704767-f15ad6e1befd?q=80&w=800",
  },
  {
    name: "Solis Champagne Citrine & Gold Stud Cufflinks",
    slug: "solis-champagne-citrine-cufflinks",
    sku: "LUX-CUF-1009",
    categorySlug: "cufflinks",
    brandSlug: "solis",
    price: 8900,
    compareAtPrice: 10800,
    shortDescription: "Faceted cushion-cut champagne citrine gems in 18K yellow gold bezels.",
    description:
      "Warm golden light reflections perfect for black-tie galas, weddings, and celebratory formal events.",
    featured: false,
    localImage: "/images/products/cufflinks/solis-champagne-citrine-cufflinks.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1490367532201-b9bc1dc483f6?q=80&w=800",
  },
  {
    name: "Chronos & Co Engraved Nautical Anchor Cufflinks",
    slug: "chronos-co-maritime-anchor-cufflinks",
    sku: "LUX-CUF-1010",
    categorySlug: "cufflinks",
    brandSlug: "chronos-co",
    price: 5800,
    compareAtPrice: 7000,
    shortDescription: "Engraved maritime anchor insignia in marine-grade 316L steel.",
    description:
      "Clean mirror polish with contrasting micro-sandblasted anchor engraving. Resists saltwater corrosion and tarnishing.",
    featured: false,
    localImage: "/images/products/cufflinks/chronos-co-maritime-anchor-cufflinks.jpg",
    unsplashUrl: "https://images.unsplash.com/photo-1598850252257-99801557eecb?q=80&w=800",
  },
];
